### ISSUE TITLE
delete legacy2016 branch?

### ISSUE THREAD

**Issue by yongbinfeng** [albertobelloni/WG_Analysis#70]
since everyone is using legacy2016 now I would propose we delete the legacy2016 branch and keep track of master.

**Comment by albertobelloni** [comment]
Hi Yongbin,

do you mean merge the legacy2016 with master, and then remove the branch? Best,

Alberto

**Comment by yongbinfeng** [comment]
ah sorry for the confusion. Legacy2016 has been merged to the master branch already. Just in case anyone is still on legacy2016, it might be good to switch to master and sync? (Not urgent)

**Comment by albertobelloni** [comment]
Moved to master, and abandoned legacy2016
